# Site settings
title: LRH Blog                     #你博客的标题
SEOTitle: 林锐鸿 | LRH Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: You@gmail.com    
description: "不是因为看见，所以相信，而是因为相信，所以看见。"              #网站介绍
keyword: "林锐鸿,LRH,JAVA" #关键词
url: "https://153011490.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
github_repo: "https://github.com/153011490/153011490.github.io" # you code repository

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "备胎是有价值的。"
sidebar-avatar:/img/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g

# SNS settings
RSS: false
weibo_username:     杨梅蘸着酱油
#zhihu_username:     
#github_username:    
#facebook_username:  
#jianshu_username:   
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: b36ce92313b7aba28547                            #生成的clientID
  clientSecret: e400002a6e4e0fbee402961333cfba0d3b711e0c    #生成的clientSecret
  repo: 153011490.github.io    #仓库名称
  owner: 153011490    #github用户名
  admin: 153011490
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b69072ac13f4dfa9f4e5863cd6275ceb






# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "微博",
        href: "https://weibo.com/u/6549935117?is_all=1"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
